apiVersion: v1
kind: Namespace
metadata:
  name: project-faq
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: csv-api
  namespace: project-faq
  labels:
    app: faq-exporter
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - HEAD
      path: /.*
  service:
    host: csv-api
    name: csv-service
    port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faq-exporter
  namespace: project-faq
  labels:
    app: faq-exporter
spec:
  selector:
    matchLabels:
      app: faq-exporter
  template:
    metadata:
      labels:
        app: faq-exporter
    spec:
      containers:
        - name: csv
          image: ghcr.io/sap-samples/kyma-mtx-faq-exporter:latest
          resources:
            requests:
              memory: 32Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 8081
          env:
            - name: CSV_ODATA_URL
              value: http://faq-backend.project-faq:8080

---
apiVersion: v1
kind: Service
metadata:
  name: csv-service
  namespace: project-faq
  labels:
    app: faq-exporter
spec:
  type: ClusterIP
  selector:
    app: faq-exporter
  ports:
    - port: 80
      targetPort: 8081

---
